# Generated by Django 4.1.3 on 2024-03-06 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JBApp', '0002_department_hod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hod',
            name='department',
        ),
        migrations.AddField(
            model_name='hod',
            name='dptmnt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JBApp.department'),
        ),
    ]
