# Generated by Django 4.1.3 on 2024-03-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JBApp', '0007_election_eroll_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='election_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
