# Generated by Django 4.1.3 on 2024-03-07 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JBApp', '0009_objection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='election_date',
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_date', models.DateField(null=True)),
                ('erollAddDate', models.DateField(null=True)),
                ('objectionAcceptDate', models.DateField(null=True)),
                ('nominationDate', models.DateField(null=True)),
                ('nomiWithdrawDate', models.DateField(null=True)),
                ('campaignDate', models.DateField(null=True)),
                ('campaignEndDate', models.DateField(null=True)),
                ('resultPublishingDate', models.DateField(null=True)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JBApp.election')),
            ],
        ),
    ]
