# Generated by Django 4.1.3 on 2024-03-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JBApp', '0011_election_campaigndate_election_campaignenddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='nominationDate',
            new_name='nomination_LastDate',
        ),
        migrations.AddField(
            model_name='election',
            name='nomination_StartDate',
            field=models.DateField(null=True),
        ),
    ]
