# Generated by Django 4.1.3 on 2024-03-07 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JBApp', '0012_rename_nominationdate_election_nomination_lastdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
                ('fac_status', models.CharField(max_length=20)),
                ('hod_status', models.CharField(max_length=20)),
                ('admin_status', models.CharField(max_length=20)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JBApp.election')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JBApp.student')),
            ],
        ),
    ]
