# Generated by Django 4.1.3 on 2024-03-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JBApp', '0013_nomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='proposer',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='seconder',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
