# Generated by Django 4.1.3 on 2024-03-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JBApp', '0014_nomination_proposer_nomination_seconder'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='admin_status',
            field=models.CharField(default='Not approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='fac_status',
            field=models.CharField(default='Not approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='hod_status',
            field=models.CharField(default='Not approved', max_length=20),
        ),
    ]
