# Generated by Django 4.1.3 on 2024-03-08 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JBApp', '0015_student_gender_alter_nomination_admin_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JBApp.nomination')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JBApp.student')),
            ],
        ),
    ]
