# Generated by Django 5.1.2 on 2024-10-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JBApp', '0019_nomination_cand_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='nomination',
        ),
        migrations.AddField(
            model_name='election',
            name='private_key',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='public_key_n',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='signing_key',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='verify_key',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='encrypted_vote',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='signature',
            field=models.TextField(null=True),
        ),
    ]
