# Generated by Django 5.1.2 on 2024-10-23 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JBApp', '0020_remove_vote_nomination_election_private_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JBApp.election'),
        ),
    ]
